apiVersion: v1
kind: Service
metadata:
  name: mock-app
  labels:
    app: mock-app
spec:
  type: ClusterIP
  selector:
    app: mock-app
  ports:
    - name: http
      port: 80
      targetPort: 80
